kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-depl
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: app-pod
      labels:
        app: spring
    spec:
      containers:
        - name: app
          image: soniya06/springboot-app:latest
          ports:
            - containerPort: 8080
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: PASS
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: PASS
